.\"
.\" Copyright (c) 2020 Tristan Le Guern <tleguern@bouledef.eu>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 23 2020 $
.Dt PNGBLANK 1
.Os
.Sh NAME
.Nm pngblank
.Nd generate images
.Sh SYNOPSIS
.Nm pngblank
.Op Fl gnp
.Op Fl b Ar bitdepth
.Op Fl c Ar library
.Op Fl l Ar level
.Op Fl s Ar strategy
.Ar width
.Sh DESCRIPTION
The
.Nm
utility generates fully transparent, square PNG images in various way.
By default the images are generated using true colours and a bit depth of 8.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl g
Set the colour type to grayscale.
.It Fl n
Do not generate an image, print its size in bytes instead.
.It Fl p
Set the colour type to indexed.
.It Fl b Ar bitdepth
Set the bitdepth to a specific value.
.It Fl c Ar library
Set the compression library.
Accept zlib or libdeflate, default is zlib.
.It Fl l Ar level
Set the compression level, the default value depends on the compresion library.
.It Fl s Ar strategy
Set the compression strategy (only valid for zlib).
.El
.Sh EXIT STATUS
.Ex -std pngblank
.Sh SEE ALSO
.Xr pnginfo 1
.Sh STANDARDS
.Rs
.%D 10 November 2003
.%T Portable Network Graphics (PNG) Specification (Second Edition)
.Sh AUTHORS
The
.Nm
utility was written by
.An Tristan Le Guern Aq Mt tleguern@bouledef.eu .
